SEED_YARNS = [
    {"name": "Drops Alpaca", "weight": "4 Ply", "colour": "Light Sea Green", "fibre": "Alpaca", "metres_per_ball": 167, "full_balls": 1, "part_balls": 0},
    {"name": "Drops Air", "weight": "Aran", "colour": "Pearl Grey 03", "fibre": "Alpaca/Wool/Polyamide", "metres_per_ball": 150, "full_balls": 2, "part_balls": 2},
    {"name": "Drops Alaska", "weight": "Aran", "colour": "Olive green", "fibre": "Wool", "metres_per_ball": 70, "full_balls": 0, "part_balls": 0, "extra_metres": 30, "notes": "Left over from Alex scarf"},
    {"name": "Hobbycraft Everyday", "weight": "Aran", "colour": "Sage green", "fibre": "Acrylic", "metres_per_ball": 195, "full_balls": 0, "part_balls": 1},
    {"name": "Rowan Four Seasons", "weight": "Aran", "colour": "Blue", "fibre": "Cotton/Acrylic", "metres_per_ball": 75, "full_balls": 5, "part_balls": 5, "intended_project": "Summer bag - or a top from Rowan book?"},
    {"name": "Sandnes Garn Tykke Line", "weight": "Aran", "colour": "Green", "fibre": "Cotton/Viscose/Linen", "metres_per_ball": 60, "full_balls": 14, "part_balls": 0, "intended_project": "Knit Sisu Picnic Pullover"},
    {"name": "Sirdar Hayfield Bonus Tweed", "weight": "Aran", "colour": "Teal Tweed", "fibre": "Acrylic/Wool/Viscose", "metres_per_ball": 840, "full_balls": 0, "part_balls": 1},
    {"name": "Stylecraft Special", "weight": "Aran", "colour": "Burgundy", "fibre": "Acrylic", "metres_per_ball": 196, "full_balls": 1, "part_balls": 0},
    {"name": "Aran Woollen Mill", "weight": "Aran", "colour": "Light purple tweed", "fibre": "Merino", "metres_per_ball": 225, "full_balls": 3, "part_balls": 1, "intended_project": "Maybe the Phildar tank top?", "notes": "Guess 811m"},
    {"name": "Rowan Sultano", "weight": "Chunky", "colour": "Burgundy", "fibre": "Cashmere/Silk", "metres_per_ball": 85, "full_balls": 11, "part_balls": 1},
    {"name": "Rowan Sultano", "weight": "Chunky", "colour": "Juniper", "fibre": "Cashmere/Silk", "metres_per_ball": 85, "full_balls": 7, "part_balls": 1},
    {"name": "Stylecraft Special", "weight": "Chunky", "colour": "Black", "fibre": "Acrylic", "metres_per_ball": 144, "full_balls": 8, "part_balls": 0, "intended_project": "King Cole v-neck top - pattern 6379", "notes": "Two new balls, need to unpick Wallis jumper to use other six."},
    {"name": "Stylecraft Special Babies", "weight": "Chunky", "colour": "Off-white", "fibre": "Acrylic", "metres_per_ball": 136, "full_balls": 1, "part_balls": 1, "notes": "Left over from baby blanket"},
    {"name": "Stylecraft Weekender", "weight": "Chunky", "colour": "Duck Egg", "fibre": "Acrylic", "metres_per_ball": 100, "full_balls": 5, "part_balls": 0, "intended_project": "Blanket"},
    {"name": "Stylecraft Weekender", "weight": "Chunky", "colour": "Clay", "fibre": "Acrylic", "metres_per_ball": 100, "full_balls": 0, "part_balls": 1, "extra_metres": 10, "intended_project": "Blanket"},
    {"name": "Unknown", "weight": "Chunky", "colour": "Brown", "fibre": "Acrylic", "full_balls": 0, "part_balls": 3, "notes": "Scarves?"},
    {"name": "Drops Karisma", "weight": "DK", "colour": "Greeny/blue", "fibre": "Wool", "metres_per_ball": 100, "full_balls": 0, "part_balls": 1},
    {"name": "Hobbycraft Cotton Blend Plain", "weight": "DK", "colour": "Light grey", "fibre": "Cotton/Acrylic", "metres_per_ball": 215, "full_balls": 1, "part_balls": 0},
    {"name": "King Cole Merino Blend", "weight": "DK", "colour": "Caramel 790", "fibre": "Merino", "metres_per_ball": 112, "full_balls": 1, "part_balls": 1, "notes": "Left over from scarf knit for Shelley. Superwash."},
    {"name": "Lana Grossa Bacca", "weight": "DK", "colour": "Dark blue", "fibre": "Cotton", "metres_per_ball": 120, "full_balls": 7, "part_balls": 0, "intended_project": "Rowan Skyler pattern from book"},
    {"name": "Paintbox Metallic", "weight": "DK", "colour": "Pina Colada", "fibre": "Cotton/Polyamide", "metres_per_ball": 120, "full_balls": 1, "part_balls": 0, "notes": "Left over from top mum reknitted"},
    {"name": "Rico Fashion Nature", "weight": "DK", "colour": "Beige 001", "fibre": "Acrylic/Wool/Camel/Viscose", "metres_per_ball": 233, "full_balls": 0, "part_balls": 1, "notes": "Left over from cushion cover"},
    {"name": "Stylecraft Naturals", "weight": "DK", "colour": "Pink", "fibre": "Cotton", "metres_per_ball": 105, "full_balls": 13, "part_balls": 0, "intended_project": "Stylecraft summer jumper pattern"},
    {"name": "West Yorkshire Spinners Elements", "weight": "DK", "colour": "Caribbean Sea", "fibre": "Lyocell/Wool", "metres_per_ball": 112, "full_balls": 9, "part_balls": 0, "intended_project": "Summer top from Elements pattern book"},
    {"name": "DMC", "weight": "DK", "colour": "Beige 773", "fibre": "Cotton", "metres_per_ball": 106, "full_balls": 7, "part_balls": 0, "intended_project": "A summer top?", "notes": "DK weight but thin"},
    {"name": "Drops Alpaca Silk", "weight": "Lace", "colour": "Heather (pink)", "fibre": "Alpaca/Silk", "metres_per_ball": 140, "full_balls": 1, "part_balls": 1},
    {"name": "Drops Andes", "weight": "Super Chunky", "colour": "Green mix", "fibre": "Wool/Alpaca", "metres_per_ball": 90, "full_balls": 0, "part_balls": 1},
    {"name": "Drops Eskimo", "weight": "Super Chunky", "colour": "Plum (dark purple)", "fibre": "Wool", "metres_per_ball": 50, "full_balls": 0, "part_balls": 1, "notes": "Left over from scarf knit for Tommy. Now called Snow"},
    {"name": "Drops Eskimo", "weight": "Super Chunky", "colour": "Dark Grape (purple)", "fibre": "Wool", "metres_per_ball": 50, "full_balls": 0, "part_balls": 0, "extra_metres": 20, "notes": "Now called Snow."},
    {"name": "Sublime Extra Fine Merino", "weight": "Worsted", "colour": "Aubergine", "fibre": "Merino", "metres_per_ball": 100, "full_balls": 0, "part_balls": 1, "notes": "Discontinued"},
    {"name": "Sublime Extra Fine Merino", "weight": "Worsted", "colour": "Mole", "fibre": "Merino", "metres_per_ball": 100, "full_balls": 0, "part_balls": 1, "notes": "Discontinued"},
    {"name": "Rico Creative Cotton", "weight": "Worsted", "colour": "White", "fibre": "Cotton", "metres_per_ball": 85, "full_balls": 1, "part_balls": 0, "intended_project": "Use for a stripe in a summer top?"},
    {"name": "Rico Creative Cotton", "weight": "Worsted", "colour": "Light Blue", "fibre": "Cotton", "metres_per_ball": 85, "full_balls": 0, "part_balls": 1, "intended_project": "Use for a stripe in a summer top?", "notes": "Nice and soft once knitted"},
    {"name": "Rico Creative Cotton", "weight": "Worsted", "colour": "Turquoise", "fibre": "Cotton", "metres_per_ball": 85, "full_balls": 1, "part_balls": 0, "intended_project": "Use for a stripe in a summer top?"},
]
