"""add ravelry pattern fields to yarns

Revision ID: 82d3b71293f1
Revises: dde9ec1df75e
Create Date: 2026-03-11 18:23:04.966008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d3b71293f1'
down_revision: Union[str, None] = 'dde9ec1df75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yarns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ravelry_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pattern_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pattern_author', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pattern_suggested_yarn', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pattern_yarn_weight', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pattern_image_filename', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yarns', schema=None) as batch_op:
        batch_op.drop_column('pattern_image_filename')
        batch_op.drop_column('pattern_yarn_weight')
        batch_op.drop_column('pattern_suggested_yarn')
        batch_op.drop_column('pattern_author')
        batch_op.drop_column('pattern_name')
        batch_op.drop_column('ravelry_url')

    # ### end Alembic commands ###
