"""create yarns table

Revision ID: 8bb2480fe40d
Revises: 
Create Date: 2026-03-10 14:44:27.297044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb2480fe40d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yarns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Enum('LACE', 'FOUR_PLY', 'DK', 'ARAN', 'WORSTED', 'CHUNKY', 'SUPER_CHUNKY', name='yarnweight'), nullable=False),
    sa.Column('colour', sa.String(), nullable=False),
    sa.Column('fibre', sa.String(), nullable=False),
    sa.Column('metres_per_ball', sa.Integer(), nullable=True),
    sa.Column('full_balls', sa.Integer(), nullable=False),
    sa.Column('part_balls', sa.Integer(), nullable=False),
    sa.Column('extra_metres', sa.Integer(), nullable=True),
    sa.Column('estimated_total_metres', sa.Integer(), nullable=True),
    sa.Column('intended_project', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('yarns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yarns_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yarns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yarns_id'))

    op.drop_table('yarns')
    # ### end Alembic commands ###
