"""add needle_size tension ball_weight image_url to yarns

Revision ID: dde9ec1df75e
Revises: 8bb2480fe40d
Create Date: 2026-03-10 16:18:45.411962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde9ec1df75e'
down_revision: Union[str, None] = '8bb2480fe40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yarns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needle_size_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tension', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ball_weight_grams', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yarns', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('ball_weight_grams')
        batch_op.drop_column('tension')
        batch_op.drop_column('needle_size_mm')

    # ### end Alembic commands ###
